### ISSUE TITLE
Update PathLinker control panel

### ISSUE THREAD

**Issue by jlaw9** [Murali-group/PathLinker-Cytoscape#44]
- [x] Add a dropdown menu for selecting the network to run PathLinker on
- [x] ~~Add a dropdown menu for selecting the name column to use~~
  - We will implement this in the future. See issue #42 
- [x] Add text clarifying that the user can enter node names (matching the "Name" column) as free text or select nodes in the network and click the button to add the node name to the list of sources/targets
  - change the button names to "Add selected source(s)" and "Add selected target(s)"
- [x] add a tooltip for the clear button
- [x] put the default k value of 200 in the input text field
  - can we only allow integers to be entered? That would eliminate the need for a warning/error message
- [x] put the default edge penalty in the input text field
  - 0 for additive, 1 for weighted, disabled for unweighted
- [x] change the weights text to: "weights are additive" and "weights are probabilities"
- [x] change the text of "Include ties" to "Include tied paths"
- [x] remove the option to disable subnetwork generation (after we have fixed issue #33 to keep the styles)
- [x] Add status messages (such as 'running')

**Comment by LHuang2019** [comment]
All the Java implementations on allowing only integers to entered are really wordy, clunky, and error prone (wrong caret position, unable to remove input, copy-paste, etc) It is better to give a warning/error message instead.

One alternative is to disable the submit button if user inputs any invalid data, and instead of warning message we can highlight all the fields with red background, so user knows which field they need to edit to enable submit button.

**Comment by jlaw9** [comment]
Ok let's not implement the integer only field then. 

Your suggested alternative sounds like a good option, but a bit more complicated to code. If so, then for now we can just keep giving the warning message.
