### ISSUE TITLE
Legend of PathLinker subnetworks for "sources = targets" option

### ISSUE THREAD

**Issue by michaelpierrelee** [Murali-group/PathLinker-Cytoscape#69]
Dear authors,

I am using PathLinker with an undirected network to extract a subnetwork from a subset of nodes, using the option "connect the sources to each other". My default style has white round node and PathLinker bypasses it to display yellow squares for the subset in the subnetwork.

However, some times I got cyan diamonds, while the legend used in the paper claims that diamonds are the "receptors" which I assume to be the sources (Fig 1, 2017 paper). Yet, it is confusing as the sources are identical to the targets, the network is undirected and when I increase k, the same nodes became yellow squares. I would expect to either have only yellow squares or cyan diamonds.

How should I interpret the cyan diamonds? Thank you in advance.

I could not find a detailed legend in the documentation.

Best regards.
Michaël

**Comment by jlaw9** [comment]
Hi Michael, 

Short answer: there's no difference between the yellow squares and cyan diamonds in your case. 

Since the network is undirected, the paths computed by PathLinker can be reversed and they'll have the same weight/cost. I'm guessing that some of the sources are only showing up at the start of paths when k is small, but as you increase k, they are changing to yellow squares because they then appear at the end of some path. Is that right?

We normally work with directed networks and must not have encountered this case.
